import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { UserActivityReportResponseDto } from '@/types/userActivityReport';

interface UserActivityReportMetadataProps {
  reportData: UserActivityReportResponseDto;
}

export function UserActivityReportMetadata({ reportData }: UserActivityReportMetadataProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm">
          Report Information
        </CardTitle>
      </CardHeader>
      <CardContent className="text-sm text-muted-foreground">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <span className="font-medium">Generated:</span>{' '}
            {new Date(reportData.generatedAt).toLocaleString()}
          </div>
          <div>
            <span className="font-medium">Generated By:</span>{' '}
            {reportData.generatedBy}
          </div>
          <div>
            <span className="font-medium">Department:</span>{' '}
            {reportData.departmentName}
          </div>
          <div>
            <span className="font-medium">Period:</span>{' '}
            {reportData.timePeriod}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
